### ISSUE TITLE
Add QueryCon 2019 to the Community Events

### ISSUE THREAD

**Issue by mike-myers-tob** [osql/osql-site#3]
https://osql.io/blog/official-news and the `Upcoming Community Events` should feature a link to the QueryCon 2019 announcement https://blog.trailofbits.com/2019/04/09/announcing-querycon-2019/

**Comment by mike-myers-tob** [comment]
When a PR is opened for this, let's file it against the osquery-site repo upstream as well! :-)

**Comment by Smjert** [comment]
On a second look, I would say that official-news is more about development news than events, I would put it only in `Upcoming Community Events`.
