### ISSUE TITLE
Keep community events in sync with osquery.io

### ISSUE THREAD

**Issue by Smjert** [osql/osql-site#5]
This is more a proposal/question.
What we want to do with all the community events that are still being posted to osquery.io?
We have the same community events posted up to March 2, but there's a new one and by looking at their Pull Requests there will be others.
Also we have one more than them (QueryCon, I will open a PR for it).

I guess we should keep it in sync because it will avoid confusion on what website people should look at, but we might lag a little sometimes.

**Comment by mike-myers-tob** [comment]
We could file Pull Requests to https://github.com/osquery/osquery-site for anything we add here?

**Comment by Smjert** [comment]
For keeping them in sync with us:
Sure!

For keeping us in sync with them:
Can't we do that with Slack maybe?

**Comment by mike-myers-tob** [comment]
Ah! You're right. I will go set up Slack integration for that repo. It shouldn't be too noisy.
